Repository Tempo-Platform/tempo-ironsource, pull requests merged in 2024-04, with the labels that each got.

#16 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#17 SC-2231 - Xcode Fix & Docs Update
  .github/workflows/cocoapods-release.yml
  README.md
Labels: fix

#18 Fix - MacOS Version
  .github/workflows/cocoapods-release.yml
Labels: fix

#20 Sc 2205/create privacy manifest for mediator3
  TempoAdapter/ISTempoCustomAdapter.swift
  tempo-ios-ironsource-mediation.podspec
  tempo-ironsource-mediation-adapter/Podfile.lock
  tempo-ironsource-mediation-adapter/Pods/Local Podspecs/tempo-ios-ironsource-mediation.podspec.json
  tempo-ironsource-mediation-adapter/Pods/Manifest.lock
  tempo-ironsource-mediation-adapter/Pods/Pods.xcodeproj/project.pbxproj
  tempo-ironsource-mediation-adapter/Pods/Target Support Files/tempo-ios-ironsource-mediation/ResourceBundle-TempoAdapter-tempo-ios-ironsource-mediation-Info.plist
Labels: chore
